window:
  width: 640
  height: 640
  title: "Snake Game"

grid:
  width: 20
  height: 20

colors:
  background: "#000000"
  grid: "#111111"
  select: "#00FF00"
  snake: "dark-green"
  wall: "#C8102E"
  text: "#FFFFFF"

wall: 0.2

path:
  dir: "levels"
  level: "mexico"

game:
  speed: 7
  width: 2
